// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebHook.Backend.DAL;

namespace WebHook.Backend.DAL.Migrations
{
    [DbContext(typeof(WebHookDbContext))]
    partial class WebHookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("WebHook.Backend.DAL.Models.WebHook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WebHooks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Google",
                            Url = "http:\\google.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
